name: MLOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Data Preparation
      run: python VisitWithUs_Project/data_preparation.py

    - name: Train Model
      run: python VisitWithUs_Project/train_model.py

    - name: Deploy to Hugging Face
      run: huggingface-cli upload
