name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -U huggingface_hub

    - name: Run data preparation
      run: python VisitWithUs_Project/data_preparation.py

    - name: Run model training
      run: python VisitWithUs_Project/train_model.py

    - name: Set Hugging Face token
      run: echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

    - name: Upload model to Hugging Face
      run: hf upload DrNiha555/visit_with_us model.pkl
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
